#!/usr/bin/env bash

export CONDA_EXE="/opt/miniforge3/bin/conda"
export FSLDIR="/apps/fsl/REPLACE_WITH_FSL_VERSION"
export MATLAB_EXECUTABLE="/apps/matlab/REPLACE_WITH_MATLAB_RELEASE/bin/matlab"
export DMRI_EXPECTED_FSL_VERSION="REPLACE_WITH_EXACT_FSL_VERSION"
export DMRI_EXPECTED_MATLAB_VERSION="REPLACE_WITH_EXACT_MATLAB_VERSION"
